// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::RevenueWithdrawalStateSucceeded;

impl RevenueWithdrawalStateSucceeded {
    /// This function creates an empty struct for the object RevenueWithdrawalStateSucceeded.
    pub fn new(date: i64, url: String) -> Self {
        Self { date, url }
    }
}
