// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::RevenueWithdrawalStateFailed;

impl RevenueWithdrawalStateFailed {
    /// This function creates an empty struct for the object RevenueWithdrawalStateFailed.
    pub fn new() -> Self {
        Self {}
    }
}
