// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::RevenueWithdrawalStatePending;

impl RevenueWithdrawalStatePending {
    /// This function creates an empty struct for the object RevenueWithdrawalStatePending.
    pub fn new() -> Self {
        Self {}
    }
}
