// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::StarTransaction;
use crate::types::StarTransactions;

impl StarTransactions {
    /// This function creates an empty struct for the object StarTransactions.
    pub fn new(transactions: Vec<StarTransaction>) -> Self {
        Self { transactions }
    }
}
