// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

#![allow(clippy::too_many_arguments, clippy::new_without_default)]
use crate::types::TransactionPartnerFragment;

impl TransactionPartnerFragment {
    /// This function creates an empty struct for the object TransactionPartnerFragment.
    pub fn new() -> Self {
        Self {
            withdrawal_state: None,
        }
    }
}
