// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// The withdrawal is in progress.
/// <https://core.telegram.org/bots/api#revenuewithdrawalstatepending>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RevenueWithdrawalStatePending {}
