// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// The withdrawal failed and the transaction was refunded.
/// <https://core.telegram.org/bots/api#revenuewithdrawalstatefailed>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RevenueWithdrawalStateFailed {}
