// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// The withdrawal succeeded.
/// <https://core.telegram.org/bots/api#revenuewithdrawalstatesucceeded>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RevenueWithdrawalStateSucceeded {
    /// Date the withdrawal was completed in Unix time
    pub date: i64,
    /// An HTTPS URL that can be used to see transaction details
    pub url: String,
}
