// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use serde::{Deserialize, Serialize};

/// Describes a transaction with an unknown source or recipient.
/// <https://core.telegram.org/bots/api#transactionpartnerother>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct TransactionPartnerOther {}
