// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::User;
use serde::{Deserialize, Serialize};

/// Describes a transaction with a user.
/// <https://core.telegram.org/bots/api#transactionpartneruser>
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct TransactionPartnerUser {
    /// Information about the user
    pub user: User,
}
