// WARNING: THIS CODE IS AUTOGENERATED.
// DO NOT EDIT!!!

use crate::types::{TransactionPartnerFragment, TransactionPartnerOther, TransactionPartnerUser};
use serde::{Deserialize, Serialize};

/// This object describes the source of a transaction, or its recipient for outgoing transactions. Currently, it can be one of
/// - TransactionPartnerFragment
/// - TransactionPartnerUser
/// - TransactionPartnerOther
/// <https://core.telegram.org/bots/api#transactionpartner>
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "type")]
pub enum TransactionPartner {
    #[serde(rename = "fragment")]
    TransactionPartnerFragment(TransactionPartnerFragment),
    #[serde(rename = "user")]
    TransactionPartnerUser(TransactionPartnerUser),
    #[serde(rename = "other")]
    TransactionPartnerOther(TransactionPartnerOther),
}
